= Deployment of HTS

Beside the deployment of the actual HTS components (Environment
and Player), a lot of other services are deployed, to get
a running platform with all the needed software.
All artifacts to be deployed are produced during the
link:build_hts.adoc[building process] respectively maintained
TAC resources.

== Artifacts

Following artifacts are deployed to several hosts, if the
setup of the hostgroup provide special hosts for the
service to install.

- HTSEnvironment.war +
  will be deployed to the 'environment host'.
- HTSPlayer.war +
  will be deployed to the 'player host'; +
  otherwise to the 'environment host'.
- license-server-web-application.war (License Server Backend) +
  will be deployed to the 'license host'.
- lsdmrs.war, ls-security.war +
  AccountConsumption.war, hts-scoring-ear.ear +
  will be deployed to the 'lso host', which is a special host
  accumulating several miro services.
- hts_localization.sql +
  will be deployed to the 'database host'. +
  The link:deploy_translations.adoc[deployment of the translations]
  is triggered by this pipeline
  if you select to deploy this artifact.
- link:deploy_TACs.adoc[Deploy TAC files] +
  TAC files are deployed to the hosts: Environment, Player
  Support-Tools.
  The deployment is triggered by this pipeline
  if you select to deploy them.
- Support-tools +
  look: https://gitlab.hogrefe.de/arcadia-projects/supporttools

==
==