= CICD Pipelines
:toc:

== Existing Pipelines

All pipelines can also be triggered manually.

=== link:build_hts.adoc[HTS build]

Build all artifacts for a deployment of the whole application
stack having all up-to-date fitting to the version you want
to deploy of a given source branch.

Links:
* https://gitlab.hogrefe.de/hts-projects/hts

=== link:deploy_hts.adoc[HTS deploy]

Deploy the bundle of artifacts of the selected version to
the selected hostgroup. You can also select if you want to
start automatically the deployment of other artifacts.

Links:
* https://gitlab.hogrefe.de/hts-projects/hts-deploy

=== link:deploy_translations.adoc[Deploy translations]

Deploy the database dump containing the translation related
data, which was produced during the xref:_linkbuild_hts_adochts_build[build process]
to a hostgroup not equal to staging.

=== link:deploy_TACs.adoc[Deploy TAC files]

Deploy TAC files to given hostgroup.

Links:
* https://gitlab.hogrefe.de/hts-projects/tac-deployment

=== Supporttools

Deploy the Support tools to given hostgroup.

Links:
* https://gitlab.hogrefe.de/arcadia-projects/supporttools